---
- name: Set APT auto upgrade config file
  ansible.builtin.copy:
    src: apt/20auto-upgrades
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: u=rw,go=r

- name: Update APT cache
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true
    cache_valid_time: 1800

- name: Upgrade APT packages
  ansible.builtin.apt:
    upgrade: dist
    force_apt_get: true
    cache_valid_time: 1800
  # Retry upgrade if it fails
  register: result
  until: result is not failed
  retries: 5
  delay: 60

- name: Install packages required for usage of APT over HTTPS
  ansible.builtin.apt:
    name: "{{ apt_packages_required_for_usage_over_https }}"
    update_cache: true
    state: present
