---
- name: Configure APT
  ansible.builtin.import_tasks:
    file: apt.yml

- name: Configure system users
  ansible.builtin.include_tasks:
    file: user.yml
  vars:
    user: "{{ item }}"
  loop:
    "{{ system_additional_users }}"

- name: Configure firewall
  ansible.builtin.import_tasks:
    file: ufw.yml
