---
- name: Install UFW APT package
  ansible.builtin.apt:
    name: "{{ apt_package_ufw }}"
    update_cache: true
    state: present

- name: Deny everything and enable UFW
  community.general.ufw:
    state: enabled
    policy: deny

- name: Allow HTTP on firewall
  community.general.ufw:
    rule: allow
    port: http
    proto: tcp

- name: Allow HTTPS on firewall
  community.general.ufw:
    rule: allow
    port: https
    proto: tcp

- name: Set connection rate limiting for SSH on firewall
  community.general.ufw:
    rule: limit
    port: ssh
    proto: tcp
