---
- name: Create additional system user '{{ user }}' with SSH access
  ansible.builtin.user:
    name: "{{ user }}"
    state: present
    shell: /bin/bash
    generate_ssh_key: true
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- name: Set authorized key for user's own public SSH key for '{{ user }}'
  ansible.builtin.shell: cat /home/{{ user }}/.ssh/id_rsa.pub > /home/{{ user }}/.ssh/authorized_keys
  args:
    creates: /home/{{ user }}/.ssh/authorized_keys

- name: Set permissions on SSH authorized_keys for '{{ user }}'
  ansible.builtin.file:
    dest: /home/{{ user }}/.ssh/authorized_keys
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: u=rw,go=
