---
- name: Create additional system users with SSH access
  ansible.builtin.user:
    name: "{{ item }}"
    state: present
    shell: /bin/bash
    generate_ssh_key: true
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  loop:
    "{{ system_additional_users }}"

- name: Set authorized key for users own public SSH key
  ansible.builtin.shell: cat /home/{{ item }}/.ssh/id_rsa.pub > /home/{{ item }}/.ssh/authorized_keys
  args:
    creates: /home/{{ item }}/.ssh/authorized_keys
  loop:
    "{{ system_additional_users }}"

- name: Set permissions on SSH authorized_keys
  ansible.builtin.file:
    dest: /home/{{ item }}/.ssh/authorized_keys
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: u=rw,go=
  loop:
    "{{ system_additional_users }}"
