---
- name: Install Node.js APT package
  ansible.builtin.apt:
    name: "{{ apt_package_nodejs }}"
    update_cache: true
    state: present

- name: Create install directory for the application
  ansible.builtin.file:
    path: /opt/hello_world/
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Install application
  ansible.builtin.copy:
    src: application.js
    dest: /opt/hello_world/application.js

- name: Install SystemD unit
  ansible.builtin.template:
    src: templates/hello_world.service.j2
    dest: /etc/systemd/system/hello_world.service

- name: Enable and start service
  ansible.builtin.service:
    name: hello_world
    enabled: true
    state: started
