---
version: 3

images:
  base_image:
    name: quay.io/fedora/fedora:41

dependencies:
  python_interpreter:
    package_system: "python3.13"
    python_path: "/usr/bin/python3.13"
  ansible_core:
    package_pip: ansible-core==2.14.8
  ansible_runner:
    package_pip: ansible-runner
  system:
  - openssh-clients
  - sshpass
