- name: Common configuration
  hosts: axolotl
  roles:
    - common

- name: Let's Encrypt certificates with Certbot
  hosts: axolotl
  roles:
    - role: geerlingguy.certbot
      when: use_letsencrypt_certificates == true

- name: PHP and Apache
  hosts: axolotl
  roles:
    - php
    - apache

- name: MariaDB
  hosts: axolotl
  roles:
    - mariadb

- name: WordPress
  hosts: axolotl
  roles:
    - wordpress

- name: Hello World with Node.js
  hosts: axolotl
  roles:
    - hello_world

- name: BookStack
  hosts: axolotl
  roles:
    - bookstack
