- name: Common configuration
  hosts: axolotl
  roles:
    - common

- name: PHP and Apache
  hosts: axolotl
  roles:
    - php
    - apache

- name: MariaDB
  hosts: axolotl
  roles:
    - mariadb

- name: WordPress
  hosts: axolotl
  roles:
    - wordpress
