---
#######
# APT #
#######

apt_package_ufw: ufw

apt_package_php: php-fpm
apt_packages_php_extensions:
  - php-mysql
  - php-curl
  - php-gd
  - php-mbstring
  - php-xml
  - php-xmlrpc
  - php-soap
  - php-intl
  - php-zip

apt_package_apache: apache2
apt_packages_apache_modules:
  - libapache2-mod-fcgid

##########
# System #
##########

system_additional_users:
  - user1
  - user2
  - user3

##########
# Apache #
##########

apache_service_name: apache2
apache_owner: www-data
apache_group: "{{ apache_owner }}"

apache_disabled_modules:
  - mpm_prefork

apache_enabled_modules:
  - rewrite
  - ssl
  - mpm_event

apache_enabled_configuration_files:
  - php8.2-fpm

apache_virtual_hosts_https:
  - name: wp.example.com
