---
use_letsencrypt_certificates: false

certbot_install_method: package
certbot_auto_renew: true
certbot_auto_renew_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
certbot_auto_renew_hour: "2"
certbot_auto_renew_minute: "42"
certbot_create_if_missing: true
certbot_create_method: standalone
certbot_testmode: false
certbot_hsts: false
certbot_admin_email: admin@example.com
certbot_certs:
  - domains:
     - "{{ wordpress_host_name }}"
  - domains:
     - "{{ hello_world_host_name }}"
  - domains:
     - "{{ bookstack_host_name }}"
certbot_create_standalone_stop_services:
  - "{{ apache_service_name }}"
